import ProjectDescription

public extension Project {
    /// Factory for a multiplatform (iOS + macOS) application project, complete
    /// with unit-test and UI-test targets and a shared, coverage-enabled scheme.
    ///
    /// A new app's `Project.swift` is then ~10 lines:
    /// ```swift
    /// let project = Project.app(name: "MyApp", bundleIdSuffix: "myapp", dependencies: [...])
    /// ```
    static func app(
        name: String,
        bundleIdSuffix: String,
        displayName: String? = nil,
        dependencies: [TargetDependency] = []
    ) -> Project {
        let bundleId = "\(Constants.organizationIdentifier).\(bundleIdSuffix)"

        return Project(
            name: name,
            organizationName: Constants.organizationName,
            settings: .base,
            targets: [
                .target(
                    name: name,
                    destinations: Constants.destinations,
                    product: .app,
                    bundleId: bundleId,
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .extendingDefault(with: [
                        "CFBundleDisplayName": .string(displayName ?? "$(PRODUCT_NAME)"),
                        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
                        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
                        "UILaunchScreen": [:],
                        "CFBundleDevelopmentRegion": "zh-Hans",
                        // App uses only standard HTTPS — declare exempt so uploads
                        // skip the manual export-compliance question.
                        "ITSAppUsesNonExemptEncryption": false,
                    ]),
                    sources: ["Sources/**"],
                    resources: ["Resources/**"],
                    dependencies: dependencies,
                    settings: .settings(base: ["ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon"])
                ),
                .target(
                    name: "\(name)Tests",
                    destinations: Constants.destinations,
                    product: .unitTests,
                    bundleId: "\(bundleId).tests",
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .default,
                    sources: ["Tests/**"],
                    dependencies: [.target(name: name)]
                ),
                .target(
                    name: "\(name)UITests",
                    destinations: Constants.destinations,
                    product: .uiTests,
                    bundleId: "\(bundleId).uitests",
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .default,
                    sources: ["UITests/**"],
                    dependencies: [.target(name: name)]
                ),
            ]
            // Schemes are auto-generated by Tuist: a shared scheme per target
            // with its associated tests and a correct, dependency-ordered build
            // graph (a hand-rolled scheme missed the cross-project build order).
        )
    }
}
