import ProjectDescription

public extension Project {
    /// Factory for a shared, reusable feature/core module with its own test
    /// target and scheme. Modules are dynamic frameworks: Tuist auto-embeds them
    /// in the consuming app and sets module search paths, which avoids the
    /// static-framework "no such module" race under Xcode's explicit modules.
    ///
    /// ```swift
    /// let project = Project.module(name: "AppCore")
    /// ```
    static func module(
        name: String,
        product: Product = .framework,
        resources: ResourceFileElements? = nil,
        dependencies: [TargetDependency] = [],
        targetSettings: SettingsDictionary = [:]
    ) -> Project {
        let bundleId = "\(Constants.organizationIdentifier).\(name.lowercased())"

        return Project(
            name: name,
            organizationName: Constants.organizationName,
            settings: .base,
            targets: [
                .target(
                    name: name,
                    destinations: Constants.destinations,
                    product: product,
                    bundleId: bundleId,
                    deploymentTargets: Constants.deploymentTargets,
                    sources: ["Sources/**"],
                    resources: resources,
                    dependencies: dependencies,
                    settings: targetSettings.isEmpty ? nil : .settings(base: targetSettings)
                ),
                .target(
                    name: "\(name)Tests",
                    destinations: Constants.destinations,
                    product: .unitTests,
                    bundleId: "\(bundleId).tests",
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .default,
                    sources: ["Tests/**"],
                    dependencies: [.target(name: name)],
                    // @testable import rebuilds the module's interface, so the
                    // tests need the same search paths (e.g. modulemap shims).
                    settings: targetSettings.isEmpty ? nil : .settings(base: targetSettings)
                ),
            ]
            // Schemes auto-generated by Tuist (see Project+App for rationale).
        )
    }
}
