import ProjectDescription

public extension Project {
    /// Factory for a multiplatform (iOS + macOS) application project, complete
    /// with unit-test and UI-test targets and a shared, coverage-enabled scheme.
    ///
    /// A new app's `Project.swift` is then ~10 lines:
    /// ```swift
    /// let project = Project.app(name: "MyApp", bundleIdSuffix: "myapp", dependencies: [...])
    /// ```
    static func app(
        name: String,
        bundleIdSuffix: String,
        displayName: String? = nil,
        launchBackgroundColorName: String? = nil,
        dependencies: [TargetDependency] = [],
        additionalResources: [ResourceFileElement] = [],
        storeKitConfigurationPath: Path? = nil
    ) -> Project {
        let bundleId = "\(Constants.organizationIdentifier).\(bundleIdSuffix)"

        // A solid launch-screen background (an asset-catalog color) so the
        // static system launch → in-app splash handoff has no white flash.
        // Empty (system default) when unset.
        let launchScreen: Plist.Value
        if let launchBackgroundColorName {
            let colorValue: Plist.Value = .string(launchBackgroundColorName)
            launchScreen = .dictionary(["UIColorName": colorValue])
        } else {
            launchScreen = .dictionary([:])
        }

        // Schemes are normally auto-generated by Tuist (shared, with a correct
        // dependency-ordered build graph). A StoreKit configuration can only
        // be attached to an explicit scheme, so one is declared exactly then —
        // with implicit dependencies enabled to keep the build order correct.
        var schemes: [Scheme] = []
        if let storeKitConfigurationPath {
            schemes.append(.scheme(
                name: name,
                shared: true,
                buildAction: .buildAction(targets: [.init(stringLiteral: name)]),
                testAction: .targets(
                    [.init(stringLiteral: "\(name)Tests"), .init(stringLiteral: "\(name)UITests")],
                    options: .options(coverage: true)
                ),
                runAction: .runAction(
                    configuration: "Debug",
                    executable: .init(stringLiteral: name),
                    options: .options(storeKitConfigurationPath: storeKitConfigurationPath)
                )
            ))
        }

        return Project(
            name: name,
            organizationName: Constants.organizationName,
            settings: .base,
            targets: [
                .target(
                    name: name,
                    destinations: Constants.destinations,
                    product: .app,
                    bundleId: bundleId,
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .extendingDefault(with: [
                        "CFBundleDisplayName": .string(displayName ?? "$(PRODUCT_NAME)"),
                        "CFBundleShortVersionString": "$(MARKETING_VERSION)",
                        "CFBundleVersion": "$(CURRENT_PROJECT_VERSION)",
                        "UILaunchScreen": launchScreen,
                        "CFBundleDevelopmentRegion": "zh-Hans",
                        // 聆听 keeps reading while the screen locks / app
                        // backgrounds (the AVAudioSession is `.playback`).
                        "UIBackgroundModes": .array([.string("audio")]),
                        // App uses only standard HTTPS — declare exempt so uploads
                        // skip the manual export-compliance question.
                        "ITSAppUsesNonExemptEncryption": false,
                    ]),
                    sources: ["Sources/**"],
                    resources: .resources(["Resources/**"] + additionalResources),
                    dependencies: dependencies,
                    settings: .settings(base: ["ASSETCATALOG_COMPILER_APPICON_NAME": "AppIcon"])
                ),
                .target(
                    name: "\(name)Tests",
                    destinations: Constants.destinations,
                    product: .unitTests,
                    bundleId: "\(bundleId).tests",
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .default,
                    sources: ["Tests/**"],
                    dependencies: [.target(name: name)]
                ),
                .target(
                    name: "\(name)UITests",
                    destinations: Constants.destinations,
                    product: .uiTests,
                    bundleId: "\(bundleId).uitests",
                    deploymentTargets: Constants.deploymentTargets,
                    infoPlist: .default,
                    sources: ["UITests/**"],
                    dependencies: [.target(name: name)]
                ),
            ],
            schemes: schemes
        )
    }
}
